---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

# Setup/install tasks.
- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- import_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Exim4 Configuration
  template:
    src: 'update-exim4.conf.j2'
    dest: '{{ exim_path }}/{{ exim_configuration_file }}'
  become: true
  tags:
    - exim
  notify:
    - update exim4.conf
    - restart exim4

- name: Create catch all configuration
  template:
    src: 'conf.d/router/01_exim4-config_catch_all'
    dest: "{{ exim_path }}/conf.d/router/01_exim4-config_catch_all"
  when: (exim4_catch_all_email is defined) and exim4_catch_all_email
  tags:
    - exim
  notify: update exim4.conf

- name: Delete catch all configuration
  file:
    path: "{{ exim_path }}/conf.d/router/01_exim4-config_catch_all"
    state: absent
  when: (not exim4_catch_all_email is defined) or (not exim4_catch_all_email)
  tags:
    - exim
  notify: update exim4.conf

- name: Create /etc/passwd.client
  template:
    src: passwd.client
    dest: "{{ exim_path }}/passwd.client"
    group: "{{ exim_group }}"
  when: ansible_os_family == "Debian"
  tags:
    - exim
  notify: update exim4.conf

- name: Configure ACLs and main configuration
  template:
    src: "conf.d/{{ item }}"
    dest: "{{ exim_path }}/conf.d/{{ item }}"
  with_items:
    - acl/30_exim4-config_check_rcpt
    - acl/31_exim4-config_check_not_smtp
    - main/03_exim4-config_extra_options
  notify: update exim4.conf
