---
# handlers file for exim4
- name: update exim4.conf
  shell: /usr/sbin/update-exim4.conf
  become: true

  # Exim4
- name: restart exim4
  action: service name=exim4 state=restarted
  become: true

- name: update exim4.aliases
  shell: newaliases
  become: true
